; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32-s3-n16r16

[env]
platform = espressif32
framework = arduino
monitor_speed = 9600
lib_ldf_mode = deep+
extra_scripts = pre:scripts/patch_esp_reverse_tunnel.py
build_unflags = 
	-std=gnu++11
	-std=gnu++14
;upload_port = COM12
;monitor_port = COM12
lib_deps = 
	ESP32Async/AsyncTCP@^3.4.10
	ESP32Async/ESPAsyncWebServer
	ayushsharma82/ElegantOTA@^3.1.7
	dennis-ard/Arducam_Mega@^2.0.9
	adafruit/Adafruit GFX Library@^1.12.5
	adafruit/RTClib@^2.1.4
	bblanchon/ArduinoJson@^7.2.2
	mcendu/LCDI2C_Multilingual_MCD@^2.1.0
	locple/LiquidCrystal I2C Multilingual@^2.0.2
	aki237/Adafruit_ESP32_SH1106@^1.0.2
	https://github.com/playmiel/ESP-Reverse_Tunneling_Libssh2.git
	https://github.com/playmiel/libssh2_esp.git#1.1

[ssh_reverse_tunnel]
build_flags = 
	-std=gnu++17
	-I$PROJECT_PACKAGES_DIR/framework-arduinoespressif32/libraries/WiFi/src
	-DLIBSSH2_MBEDTLS
	-DHAVE_LIBSSH2_H
	-DLIBSSH2_NO_ZLIB
	-DHAVE_CONFIG_H
	-DCONFIG_ARDUHAL_ESP_LOG

[env:esp32-c3-devkitm-1]
board = esp32-c3-devkitm-1
upload_port = COM5
monitor_port = COM5
build_flags = 
	${ssh_reverse_tunnel.build_flags}
	-DORANGEBOX_BOARD_C3
	-DCORE_DEBUG_LEVEL=0
	-DELEGANTOTA_USE_ASYNC_WEBSERVER=1

[env:esp32-s3-n32r16]
board = esp32-s3-devkitc-1
board_upload.flash_size = 32MB
board_upload.maximum_size = 33554432
board_build.flash_mode = opi
board_build.arduino.memory_type = opi_opi
board_build.partitions = default_16MB.csv
build_flags = 
	${ssh_reverse_tunnel.build_flags}
	-DORANGEBOX_BOARD_S3
	-DBOARD_HAS_PSRAM
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DCORE_DEBUG_LEVEL=0
	-DELEGANTOTA_USE_ASYNC_WEBSERVER=1

[env:esp32-s3-n16r16]
;extends = env:esp32-s3-n32r16
board = esp32-s3-devkitc-1
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.flash_mode = qio
board_build.arduino.memory_type = qio_opi
board_build.partitions = default_16MB.csv
upload_port = COM12
monitor_port = COM12

build_flags = 
	${ssh_reverse_tunnel.build_flags}
	-DORANGEBOX_BOARD_S3U
	-DBOARD_HAS_PSRAM
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DCORE_DEBUG_LEVEL=0
	-DELEGANTOTA_USE_ASYNC_WEBSERVER=1

[env:vpn-reverse-tunnel-stub]
board = esp32-s3-devkitc-1
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.flash_mode = opi
board_build.arduino.memory_type = opi_opi
board_build.partitions = default_16MB.csv
lib_deps = 
	https://github.com/playmiel/ESP-Reverse_Tunneling_Libssh2.git
	https://github.com/playmiel/libssh2_esp.git#1.1
build_flags = 
	${ssh_reverse_tunnel.build_flags}
	-DORANGEBOX_BOARD_S3
	-DCORE_DEBUG_LEVEL=5
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DBOARD_HAS_PSRAM
build_src_filter = 
	-<*>
	+<vpn_manager.cpp>
	+<../test/vpn_reverse_tunnel_stub.cpp>

[env:qr-scanner-stub]
board = esp32-s3-devkitc-1
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.flash_mode = qio
board_build.arduino.memory_type = qio_opi
board_build.partitions = default_16MB.csv
upload_port = COM11
monitor_port = COM11
lib_deps = 
build_flags = 
	-std=gnu++17
	-DORANGEBOX_BOARD_S3U
	-DBOARD_HAS_PSRAM
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DCORE_DEBUG_LEVEL=0
build_src_filter = 
	-<*>
	+<qr_scanner.cpp>
	+<../test/qr_scanner_stub.cpp>
